### ISSUE TITLE
Camels with carts unable to sprint due to Slow mode

### ISSUE THREAD

**Issue by 6xolotl** [jmb05/nifty-carts#31]
title. i tried to edit the range myself (since the og mod is open source and has an MIT license i assumed that was on the table, very sorry if it isnt!) but it almost made me slam my head into a wall because i am not a programming girlie.

(i would delete the previous issue i filed, but github literally wont let me, so you can delete it if you want.)

ideally, the range would be big enough to allow disabling the speed loss entirely. then again, just adding a config option to disable the speed loss (so that your mount moves at normal speeds whether its carrying a cart or not) might be easier.

also, i dont understand the point of slow mode, but obviously im not gonna ask for it to be removable, just that it be toggleable. the whole purpose of carts is efficiency, i want to be able to sprint while carrying them 💔

**Comment by jmb05** [comment]
I am not really sure what the purpose of the slow mode is in the first place. It is just a feature I copied over from the original mod. It may have been a tradeoff. So that a horse couldn't pull a cart very fast because it would be heavy. But then you can't even sprint on minecraft horses. It is just an illusion where the FOV changes but the speed stays the same (this has been fixed in recent versions, now the FOV doesn't change). So I am not sure this is a big issue except if you are using a mount from another mod which allows sprinting. 
I will probably just make the key binding for the slow mode configurable so if people want they can change it.

**Comment by jmb05** [comment]
Also, setting the slow_speed option in the config to 0 should effectively disable the slow mode

**Comment by 6xolotl** [comment]
oh, im using a camel, so no modded mount here.
funnily enough, i tried changing the option in the config to 0, but nothing changed. i knew i shouldve filed that speed bug i found before i started fucking with the code, thats probably why it didnt work ☠️
give me a little bit and ill file a bug report for that!

**Comment by jmb05** [comment]
I see now how the camel could cause issues. I'll probably just map the slow mode to a different key as the default.
I don't think there is a need to file a new report, we can adapt this one for the issue at hand.
